server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhangxinde_com?useSSL=false
    hikari:
      username: root
      password: root
  jpa:
    show-sql: false
  freemarker:
    cache: true