server:
  port: 80
  http2:
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    hikari:
      username: root
      password: root
  mvc:
    favicon:
      enabled: true
  freemarker:
    suffix: .html
    cache: false
    settings:
      template_exception_handler: rethrow
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
    timeout: 5000 # 连接超时
    database: 0
    jedis:
      pool:
        min-idle: 1
        max-idle: 20
        max-active: 20
        max-wait: 60000
          