server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    hikari:
      username: root
      password: root
  jpa:
    show-sql: true
  freemarker:
    cache: false