server:
  port: 80
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    hikari:
      username: root
      password: root
  mvc:
    favicon:
      enabled: true
  freemarker:
    suffix: .html
    cache: false
    settings:
      template_exception_handler: rethrow
  jpa:
    show-sql: true